codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
      nginx:
        target: auto
        threshold: 0%
        paths:
          - "internal/nginx/"
      controller:
        target: auto
        threshold: 0%
        paths:
          - "internal/ingress/controller/"
      annotations:
        target: auto
        threshold: 0%
        paths:
          - "internal/ingress/annotations/"
      k8s:
        target: auto
        threshold: 0%
        paths:
          - "internal/k8s/"
      admission:
        target: auto
        threshold: 0%
        paths:
          - "internal/admission/"
    patch:
      default:
        target: 80%
        threshold: 0%

ignore:
  - "test/**/*"
  - "images/**/*"
  - "**/*_test.go"
  - "docs/**/*"
  - "vendor/**/*"
  - "hack/**/*"
  - "build/**/*"
  - "rootfs/**/*"
  - "**/zz_generated*.go"
  - "**/generated.proto"
  - "cmd/plugin/**/*"
