[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).

"""
body = """
{% if version %}\
    ## [{{ version }}](https://github.com/forkline/ingress-nginx/tree/{{ version }}) - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## [unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}
        - {{ commit.message | upper_first }}\
            {% if commit.scope %} ({{ commit.scope }}){% endif %}\
            ([{{ commit.id | truncate(length=7, end="") }}](https://github.com/forkline/ingress-nginx/commit/{{ commit.id }}))
    {% endfor %}
{% endfor %}\n
"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false
commit_preprocessors = [
    { pattern = "^release\\(release\\): prepare ", replace = "release: prepare" },
    { pattern = "^release: prepare v[0-9]+.*", skip = true },
    { pattern = " \\(#\\d+\\)$", replace = "" },
    { pattern = "(?s)\\n\\n.*", replace = "" },
]
commit_parsers = [
    { message = "^feat", group = "<!-- 0 -->Added" },
    { message = "^fix", group = "<!-- 1 -->Fixed" },
    { message = "^docs", group = "<!-- 2 -->Documentation" },
    { message = "^build", group = "Build" },
    { message = "^refactor", group = "Refactor" },
    { message = "^release", skip = true },
    { message = "^style", group = "Styling" },
    { message = "^test", group = "Testing" },
    { message = "^chore", group = "<!-- 3 -->Chore" },
    { message = "^ci", group = "<!-- 4 -->CI" },
    { message = "^perf", group = "Performance" },
]
protect_breaking_commits = false
filter_commits = false
sort_commits = "oldest"
